on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  notify:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.archive_name }}
          path: ./artifact
      - name: Send Telegram Notification with Build File
        env: 
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |          
          FILE_PATH="./artifact/firmware.zip"
          CAPTION="Build completed with status: ${{ needs.build.outcome }}."

          RESPONSE=$(curl 
              --silent
              --write-out '%{http_code}' 
              --output response_body.txt -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
              -F chat_id="${TELEGRAM_CHAT_ID}" \
              -F document=@"${FILE_PATH}" \
              -F caption="${CAPTION}") 

          # Check the HTTP response code
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Error: Failed to send notification. HTTP Response Code: $RESPONSE"
            echo "Response Body: $(cat response_body.txt)"
            exit 1
          else
            echo "Telegram notification sent successfully."
          fi
