on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  notify:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.archive_name }}
          path: ./artifact
      - name: Send Telegram Notification with Build File
        env: 
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -e "./artifact/firmware.zip" ]; then
            echo "File exists."
          else
            echo "File does not exist." && exit 1
          fi
          
          FILE_PATH="./artifact/firmware.zip"

          BUILD_STATUS="${{ needs.build.outcome }}"
          CAPTION="Build completed with status: $BUILD_STATUS."
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
               -F chat_id="${TELEGRAM_CHAT_ID}" \
               -F document=@"${FILE_PATH}" \
               -F caption="${CAPTION}"
        
          
